/* ATG 116 POC V1.0.1 | 2026-10-01 | Offline, synthetic data only */
'use strict';
(()=>{
if(!ATGAuth.requireLogin())return;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='atg116.demo.v1';let cases,logs;let storageWarning='';
try{const state=JSON.parse(localStorage.getItem(KEY));if(state?.version==='1.0.1'&&Array.isArray(state.cases)&&state.cases.length&&Array.isArray(state.logs)){cases=state.cases;logs=state.logs;}else{cases=structuredClone(ATG_SEED);logs=[];}}catch{cases=structuredClone(ATG_SEED);logs=[];storageWarning='瀏覽器儲存不可用或紀錄損壞；本次使用初始示範資料。';}
let page='dashboard',selected=cases[0].id,filters={tax:'全部',district:'全部',status:'全部',query:'',risk:false,min:70};
let layers={parcel:true,tax:true,building:true,changes:true};let zoom=1;let comparison=50;let years=['114','116'];let checked=new Set();
const titles={dashboard:['總覽與最新消息','延續114年首頁，集中呈現116年清查與回饋進度。'],map:['地圖清查','沿用上方模組、左側圖層、中央圖台與工具列。'],cases:['AI 疑義案件','分類結果、來源理由與人工覆核，在同一案件中完成。'],projects:['專案派送與回饋','依專案分派案件，追蹤處理進度並累積覆核標籤。'],property:['公有財產清查','公有房地產籍一致性與市有土地占用線索示範。'],data:['資料更新與品質','追蹤來源版本、欄位缺漏與批次匯入狀態。'],assistant:['智慧查詢助手','依展示資料查詢；固定意圖規則示範，尚未串接LLM。'],governance:['模型與稽核紀錄','分類模型、回饋資料與操作歷程的版本治理。'],versions:['文件與版本紀錄','來源對照、操作說明與成果版更。']};
function stamp(){return new Date().toLocaleString('sv-SE',{timeZone:'Asia/Taipei'})+' +08:00';}
function save(){try{localStorage.setItem(KEY,JSON.stringify({version:'1.0.1',cases,logs}));}catch{toast('本次變更僅保留於記憶體；瀏覽器儲存不可用。');}}
function audit(action,id,detail){logs.unshift({time:stamp(),user:'geoinfor',action,case:id||'—',detail});save();}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.add('hidden'),4300);}
function badge(text){return `<span class="badge ${text==='待覆核'?'amber':text==='資料待補'?'red':''}">${esc(text)}</span>`;}
function fmt(n){return Number(n).toLocaleString('zh-TW');}
function stats(){return {total:cases.length,pending:cases.filter(c=>c.status==='待覆核').length,assigned:cases.filter(c=>c.owner!=='未分派').length,confirmed:cases.filter(c=>c.feedback?.result==='確認稅務異常').length,negative:cases.filter(c=>c.feedback?.result==='確認無稅務異常').length,quality:cases.filter(c=>c.dataQuality!=='完整').length,closed:cases.filter(c=>c.status==='已覆核').length};}
function filtered(){return cases.filter(c=>(filters.tax==='全部'||c.tax===filters.tax)&&(filters.district==='全部'||c.district===filters.district)&&(filters.status==='全部'||c.status===filters.status)&&(!filters.query||`${c.id} ${c.category} ${c.scenario} ${c.target} ${c.owner}`.includes(filters.query))&&(!filters.risk||(c.score!==null&&c.score>=filters.min))).sort((a,b)=>filters.risk?(b.score??-1)-(a.score??-1):a.id.localeCompare(b.id));}
function selectOptions(arr,value){return arr.map(v=>`<option ${v===value?'selected':''}>${esc(v)}</option>`).join('');}
function header(){const t=titles[page];return `<div class="pagehead"><div><div class="eyebrow">ATG / 116 WORKSPACE</div><h1>${t[0]}</h1><p class="muted" style="margin:0">${t[1]}</p></div><div class="actions"><a href="AI模型建構設計.html" target="_blank" rel="noopener">AI 設計文件 ↗</a></div></div><div class="notice">展示模式：案件、圖資、分類與推論分數均為模擬資料。116年建構分類與回饋；117年排序展望可另外開啟。</div>${storageWarning?`<div class="notice warning">${storageWarning}</div>`:''}`;}
function navigate(name){if(!titles[name])name='dashboard';page=name;location.hash=name;render();}
function render(){if(!ATGAuth.requireLogin())return;$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#workspace').innerHTML=header()+views[page]();bind();}
function dashboard(){const s=stats();return `<div class="cards"><div class="card"><small>示範候選案件</small><strong>${s.total}<span class="unit"> 件</span></strong><span class="badge">全部模擬</span></div><div class="card"><small>待人工覆核</small><strong>${s.pending}<span class="unit"> 件</span></strong><small>由承辦人審認稅務結果</small></div><div class="card"><small>已分派案件</small><strong>${s.assigned}<span class="unit"> 件</span></strong><small>在專案派送中調整</small></div><div class="card"><small>已覆核標籤</small><strong>${s.closed}<span class="unit"> 件</span></strong><small>異常 ${s.confirmed} / 無異常 ${s.negative}</small></div></div><div class="grid2"><section class="panel"><div class="panelhead"><h2>116年度清查工作流程</h2><span class="badge">人機協作</span></div><div class="steps"><div class="step"><b>01</b>來源匯入與品質檢核</div><div class="step"><b>02</b>規則輔助與疑義分類</div><div class="step"><b>03</b>派案與人工覆核</div><div class="step"><b>04</b>結果回饋與版本留存</div></div><div class="panelhead" style="margin-top:25px"><h3>待覆核案件</h3><button data-go="cases">查看全部</button></div>${caseTable(cases.filter(c=>c.status==='待覆核').slice(0,5),false)}</section><section><div class="panel"><h2>最新消息</h2><p><span class="badge">116 / 新增</span> 疑義案件分類理由與查核結果回填。</p><p><span class="badge">116 / 深化</span> 年度比對、TAX稅種圖層與公有財產清查。</p><p><span class="badge amber">117 / 展望</span> 風險評分及智慧排序待分類與回饋成熟後導入。</p><p class="help">本頁保留114年「最新消息＋登入紀錄」資訊架構。</p></div><div class="panel"><h3>示範資料範圍</h3><div class="row"><span>房屋稅模擬案件</span><b>12 件</b></div><div class="row"><span>地價稅模擬案件</span><b>12 件</b></div><p class="help">公開版本僅含24件模擬案例，不附原始清冊、中繼資料或機關文件。</p></div></section></div><section class="panel"><h3>使用者登入紀錄（本機展示）</h3>${logTable(logs.filter(l=>l.action==='登入').slice(0,3))}</section>`;}
function filterControls(){return `<div class="filters"><label>稅種<select id="taxFilter">${selectOptions(['全部','房屋稅','地價稅'],filters.tax)}</select></label><label>行政區<select id="districtFilter">${selectOptions(['全部',...new Set(cases.map(c=>c.district))],filters.district)}</select></label><label>處理狀態<select id="statusFilter">${selectOptions(['全部','待覆核','待現勘','已覆核','資料待補'],filters.status)}</select></label><label>案件搜尋<input id="caseSearch" type="search" value="${esc(filters.query)}" placeholder="案件編號、態樣、承辦人"></label><button id="applyFilter">查詢</button><button id="clearFilter">清除條件</button></div><div class="filters"><label class="layercheck"><input id="riskToggle" type="checkbox" ${filters.risk?'checked':''}>開啟117年排序展望（模擬）</label>${filters.risk?`<label>模擬分數至少 <b id="scoreValue">${filters.min}</b><input id="scoreMin" type="range" min="0" max="100" value="${filters.min}"></label><small>缺識別資料案件不評分；分數不是經校準的機率。</small>`:''}</div>`;}
function caseTable(list,multi=true){if(!list.length)return '<div class="empty">沒有符合條件的案件。請調整查詢條件。</div>';return `<div class="tablewrap"><table><thead><tr>${multi?'<th><input type="checkbox" id="selectAll" aria-label="選取查詢結果全部案件"></th>':''}<th>案件 / 稅種</th><th>行政區 / 疑義態樣</th><th>分類提示</th><th>資料品質</th>${filters.risk?'<th>117模擬分數</th>':''}<th>承辦 / 狀態</th><th>操作</th></tr></thead><tbody>${list.map(c=>`<tr>${multi?`<td><input type="checkbox" class="caseCheck" data-id="${esc(c.id)}" ${checked.has(c.id)?'checked':''} aria-label="選取${esc(c.id)}"></td>`:''}<td><b>${esc(c.id)}</b><br><small>${esc(c.tax)}</small></td><td>${esc(c.district)}<br><small>${esc(c.scenario)}</small></td><td>${badge(c.category)}</td><td>${c.dataQuality==='完整'?badge('完整'):badge('資料待補')}</td>${filters.risk?`<td class="num">${c.score===null?'不評分':c.score}</td>`:''}<td>${esc(c.owner)}<br>${badge(c.status)}</td><td><button class="openCase" data-id="${esc(c.id)}">覆核</button><button class="locateCase" data-id="${esc(c.id)}">定位</button></td></tr>`).join('')}</tbody></table></div>`;}
function caseView(){const list=filtered();return `<section class="panel">${filterControls()}<div class="panelhead"><h2>查詢結果 <small>${list.length} 件</small></h2><div class="actions"><button id="exportCases">匯出查詢清冊</button><button data-go="projects">專案派送</button></div></div>${caseTable(list)}</section>`;}
function mapSVG(){let parcels='';for(let r=0;r<8;r++)for(let c=0;c<10;c++){let x=30+c*72,y=28+r*67;parcels+=`<rect x="${x}" y="${y}" width="67" height="61" fill="${(r+c)%4===0?'#e5e8ce':(r+c)%3===0?'#d3e6bf':'#e8e7d6'}" stroke="#aebfa5"/>`;}
let buildings='';for(let i=0;i<35;i++){const x=58+(i*79)%630,y=50+(i*101)%465;buildings+=`<rect x="${x}" y="${y}" width="${20+i%4*8}" height="24" fill="#b6c5b5" stroke="#7f9783"/>`;}
let taxes='';for(let i=0;i<16;i++)taxes+=`<rect x="${40+(i*83)%640}" y="${35+(i*91)%480}" width="62" height="54" fill="${i%3===0?'#b2d695':i%3===1?'#e4cc8b':'#a9cdda'}" opacity=".55"/>`;
const list=filtered();return `<svg id="demoMap" viewBox="0 0 800 600" role="img" aria-label="模擬宗地與案件位置示意，非實際地籍"><g transform="translate(${400-400*zoom} ${300-300*zoom}) scale(${zoom})"><rect width="800" height="600" fill="#e8ecd9"/><g ${layers.parcel?'':'display="none"'}>${parcels}</g><path d="M-20 485 C165 440 65 225 205 220 S480 180 815 60" stroke="#afd6df" stroke-width="45" fill="none"/><path d="M-20 140L820 405M315-20L535 620" stroke="#fffefa" stroke-width="32" fill="none"/><path d="M-20 140L820 405M315-20L535 620" stroke="#d8d6b7" stroke-width="2" stroke-dasharray="7 5" fill="none"/><g ${layers.tax?'':'display="none"'}>${taxes}</g><g ${layers.building?'':'display="none"'}>${buildings}</g><g ${layers.changes?'':'display="none"'}><rect x="530" y="330" width="100" height="60" fill="#e9bb73" fill-opacity="${comparison/100}" stroke="#bb7b23" stroke-width="3" stroke-dasharray="6 4"/><rect x="145" y="85" width="80" height="53" fill="#e9bb73" fill-opacity="${comparison/100}" stroke="#bb7b23" stroke-width="3" stroke-dasharray="6 4"/></g><g font-size="17" fill="#72826b"><text x="75" y="525">模擬區 A</text><text x="560" y="95">模擬區 B</text><text x="360" y="500" transform="rotate(70 360 500)">示意道路</text></g>${list.map(c=>`<g tabindex="0" role="button" aria-label="定位案件 ${esc(c.id)}" class="mapcase ${c.id===selected?'selected':''}" data-id="${esc(c.id)}"><circle cx="${c.x}" cy="${c.y}" r="13" fill="${c.dataQuality==='完整'?c.tax==='房屋稅'?'#087f73':'#c38b28':'#84918b'}"/><text x="${c.x}" y="${c.y+4}" text-anchor="middle" fill="white" font-size="10">${esc(c.id.slice(-3))}</text></g>`).join('')}</g></svg>`;}
function mapView(){const c=cases.find(c=>c.id===selected)||cases[0];return `<div class="filters"><label>稅種<select id="mapTax">${selectOptions(['全部','房屋稅','地價稅'],filters.tax)}</select></label><small>圖台顯示 ${filtered().length} 件篩選結果。點擊案件點位可查看理由。</small><button data-go="cases">開啟案件清冊</button></div><div class="mapgrid"><section class="panel layers"><h3>圖層設定</h3><span class="badge">稅籍圖資 / 參考圖資</span>${[['parcel','地籍宗地框'],['tax','TAX 地價稅稅種'],['building','建物框示意'],['changes','年度變異範圍']].map(([k,t])=>`<label class="layercheck"><input type="checkbox" data-layer="${k}" ${layers[k]?'checked':''}>${t}</label>`).join('')}<label>稅種透明度<input id="taxOpacity" type="range" min="0" max="100" value="55"></label><h3 style="margin-top:18px">年度圖資比對</h3><label>比較年度<select id="yearFrom">${selectOptions(['114','115'],years[0])}</select></label><label>目標年度<select id="yearTo">${selectOptions(['115','116'],years[1])}</select></label><label>目標年度變異呈現<input id="compareSlider" type="range" min="0" max="100" value="${comparison}"></label><p class="help">切換年度更新標題；滑桿控制變異色塊呈現。正式版改接核准年度正射影像與真實GIS服務。</p><button id="parcelHistory">地籍異動沿革</button></section><section><div class="maparea"><div id="mapSvgHost" style="height:100%">${mapSVG()}</div><div class="maplabel" id="mapYears">${years[0]} → ${years[1]} 年度 · 模擬比對</div><div class="maptools"><button id="zoomIn" aria-label="放大地圖">＋</button><button id="zoomOut" aria-label="縮小地圖">−</button><button id="mapReset" aria-label="重置地圖">⌂</button></div><div class="maplegend">● 房屋稅　<span style="color:#b78321">● 地價稅</span>　<span style="color:#84918b">● 資料待補</span><br>綠：田賦示意　黃：一般用地示意　藍：減免示意<br>橘色框：年度變異 · 點位與地籍均為示意</div></div><div class="mapfooter">SVG 離線圖台 · 無真實坐標、影像、量測或行政區界</div></section><section class="panel mapdetail"><div class="panelhead"><h3>案件資訊</h3>${badge(c.tax)}</div><h2>${esc(c.id)}</h2><p>${esc(c.scenario)}</p><div class="detailgrid"><div><small>行政區</small>${esc(c.district)}</div><div><small>處理狀態</small>${badge(c.status)}</div><div><small>分類提示</small>${esc(c.category)}</div><div><small>資料品質</small>${esc(c.dataQuality)}</div></div><h3>疑義理由（規則示意）</h3>${c.reasons.slice(0,2).map(r=>`<div class="reason">${esc(r.text)}<small>${esc(r.code)} · ${esc(r.source)}</small></div>`).join('')}<button class="primary openCase" data-id="${esc(c.id)}">開啟人工覆核</button><p class="help" style="margin-top:15px">最終是否異常由承辦人核實。示範理由不是SHAP計算結果。</p></section></div>`;}
function projects(){const list=filtered();const s=stats();return `<div class="gridEqual">${['房屋稅','地價稅'].map(t=>{const items=cases.filter(c=>c.tax===t),done=items.filter(c=>c.status==='已覆核').length;return `<section class="panel"><div class="panelhead"><h2>116${t}疑義清查</h2>${badge('116年')}</div><div class="row"><span>已覆核 / 候選</span><b>${done} / ${items.length}</b></div><div class="progress"><span style="width:${done/items.length*100}%"></span></div><p class="help" style="margin-top:12px">未分派 ${items.filter(c=>c.owner==='未分派').length} 件 · 待現勘 ${items.filter(c=>c.status==='待現勘').length} 件</p></section>`;}).join('')}</div><section class="panel"><h2>批次派送</h2>${filterControls()}<div class="filters"><label>示範承辦人<select id="assignOwner">${selectOptions(['示範承辦A','示範承辦B','示範承辦C'],'示範承辦A')}</select></label><button class="primary" id="assignCases">分派選取案件</button><small id="selectedCount">已選 ${checked.size} 件</small><button id="exportFeedback">匯出覆核回饋 JSON</button></div>${caseTable(list)}</section><section class="panel"><h3>回饋標籤成熟度（展示案件）</h3><p>已確認稅務異常 ${s.confirmed} 件、已確認無稅務異常 ${s.negative} 件、待補資料 ${cases.filter(c=>c.status==='資料待補').length} 件。待現勘與資料待補案件不直接作為訓練真值。</p><p class="help">改課稅額須於正式系統由業務查核回填；本POC不計算或推估稅額。</p></section>`;}
function property(){return `<section class="panel"><div class="panelhead"><h2>公有房地產籍一致性</h2>${badge('116新增示範')}</div><p class="muted">尚無公產清冊來源；以下三筆完全模擬，供欄位與流程討論。</p><div class="tablewrap"><table><thead><tr><th>模擬產籍標的</th><th>比對項目</th><th>查核提示</th><th>後續處理</th></tr></thead><tbody><tr><td>PUB-DEMO-01</td><td>產籍面積 / 地籍面積</td><td>記載差異須查核異動歷程</td><td><button class="propertyDetail" data-type="面積異動">檢視</button></td></tr><tr><td>PUB-DEMO-02</td><td>使用分區 / 管理用途</td><td>分區版本不一致</td><td><button class="propertyDetail" data-type="使用分區">檢視</button></td></tr><tr><td>PUB-DEMO-03</td><td>市有土地 / 私有建物框</td><td>交集且未連結使用補償紀錄</td><td><button class="propertyDetail" data-type="占用線索">檢視</button></td></tr></tbody></table></div></section><section class="panel"><h2>市有土地清查流程</h2><div class="steps"><div class="step"><b>01</b>產籍與地籍標的對應</div><div class="step"><b>02</b>建物交集與現況圖資</div><div class="step"><b>03</b>使用授權及補償紀錄核對</div><div class="step"><b>04</b>管理機關確認及現勘測量</div></div><div class="notice warning" style="margin-top:20px">圖資交集僅為線索；須核對合法使用、租約、資料日期與測量成果後，由管理機關確認。</div></section>`;}
function dataView(){return '<section class="panel"><h2>公開示範資料與品質</h2><p>本版僅使用24件模擬案件。原始機關清冊、來源檔案名稱、實際欄位結構與來源雜湊均未發布。</p><div class="notice">正式專案的資料盤點、欄位映射與品質結果須於核准環境管理；公開頁面僅展示操作流程。</div></section><div class="gridEqual"><section class="panel"><h2>示範CSV匯入</h2><p>匯入隨附的示範案件匯入.csv。僅接受DEMO編號，錯誤或重複列整批拒收。</p><label>選擇示範CSV<input id="csvImport" type="file" accept=".csv,text/csv"></label><p class="help">示範契約：case_id、tax_type、district、scenario；此契約是POC自訂格式，非原始清冊結構。</p><a href="示範案件匯入.csv" download>下載示範匯入檔</a><div id="importResult" role="status"></div></section><section class="panel"><h2>正式資料介接方向</h2><p>由Web後端檢核來源版本、權限、資料時點與定位品質，再發布分類結果；資料不足則轉人工。</p><p>本版未連接任何正式稅籍、GIS、資料交換或AI服務。</p></section></div>';}

function assistant(){return `<section class="panel"><h2>清查資料智慧查詢</h2><p class="muted">目前支援：房屋稅、地價稅、待覆核、資料待補、已覆核。查詢以本機示範案件為範圍。</p><div class="actions" style="margin-bottom:20px"><button class="promptBtn">房屋稅待覆核</button><button class="promptBtn">地價稅待覆核</button><button class="promptBtn">資料待補</button></div><form id="assistantForm" class="filters"><label style="flex:1">查詢需求<input id="assistantQuery" placeholder="例如：房屋稅待覆核" maxlength="150" required></label><button class="primary">查詢</button></form><div id="assistantAnswer" aria-live="polite"><div class="chat">請輸入清查需求。結果將顯示案件與資料依據；未知問題會提示可用範圍。</div></div></section><section class="panel"><h3>正式智慧查詢整合方向</h3><p>使用經授權的語意查詢服務解析條件，由Web API執行權限過濾後回傳案件。案件分類與LLM查詢採分離服務；不得讓模型生成未經確認的查核結果或直接執行任意SQL。</p></section>`;}
function governance(){const s=stats();return `<div class="gridEqual"><section class="panel"><h2>分類模型版本</h2><p><span class="badge amber">未訓練</span> DEMO-CLASSIFIER-0.1</p><p>本POC使用預先定義的模擬分類與規則理由。尚無模型權重、SHAP運算或有效性評估。</p><div class="detailgrid"><div><small>展示規則版本</small>DEMO-RULE-0.1</div><div><small>特徵契約版本</small>FEATURE-SCHEMA-0.1</div><div><small>示範來源快照</small>S116-DEMO-01</div><div><small>評估指標</small>尚未產生</div></div><a href="AI模型建構設計.html#evaluation">查看驗證與上線門檻</a></section><section class="panel"><h2>人工回饋與治理</h2><p>本機可用覆核標籤：${s.confirmed+s.negative} 件（全為模擬）。</p><p>正式版需由業務專家確認標籤、獨立測試集與角色授權後，才能升版及發布模型。</p><div class="actions"><button id="exportLogs">匯出本機稽核 JSON</button><button id="resetDemo">重置示範案件</button></div><p class="help" style="margin-top:12px">瀏覽器日誌可被使用者修改；正式版應使用後端不可任意覆寫的操作紀錄。</p></section></div><section class="panel"><h2>操作稽核紀錄（本機展示）</h2>${logTable(logs.slice(0,30))}</section>`;}
function logTable(list){return !list.length?'<div class="empty">尚無本機操作紀錄。</div>':`<div class="tablewrap"><table><thead><tr><th>臺北時間</th><th>帳號</th><th>動作</th><th>案件</th><th>摘要</th></tr></thead><tbody>${list.map(l=>`<tr><td>${esc(l.time)}</td><td>${esc(l.user)}</td><td>${esc(l.action)}</td><td>${esc(l.case)}</td><td>${esc(l.detail)}</td></tr>`).join('')}</tbody></table></div>`;}
function versions(){return `<section class="panel"><h2>成果文件</h2><a class="doclink" href="AI模型建構設計.html" target="_blank" rel="noopener"><strong>AI 模型建構設計 V1.0.1</strong><small>實際資料盤點、模型生命週期、API與驗收設計</small></a><a class="doclink" href="版本與交付說明.html" target="_blank" rel="noopener"><strong>版本與交付說明 V1.0.1</strong><small>功能範圍、來源差異、啟動與版更規則</small></a><a class="doclink" href="驗證紀錄.html" target="_blank" rel="noopener"><strong>驗證紀錄 V1.0.1</strong><small>本版實際測試結果與限制</small></a></section><section class="panel"><h2>版更紀錄</h2><div class="tablewrap"><table><thead><tr><th>版本</th><th>發布日期</th><th>修改內容</th><th>資料與模型狀態</th></tr></thead><tbody><tr><td>V1.0.1</td><td>2026-10-01</td><td>首次交付：登入、清查、分類覆核、派送、公產、資料與設計文件</td><td>來源清冊結構已盤點；模型尚未訓練</td></tr></tbody></table></div><p class="help">文件、展示規則、特徵及模型版本分別管理；每次調整記錄變更、影響、來源與測試結果。</p></section>`;}
const views={dashboard,map:mapView,cases:caseView,projects,property,data:dataView,assistant,governance,versions};
function openCase(id){const c=cases.find(c=>c.id===id);if(!c)return;selected=id;audit('查看案件',id,'開啟分類與覆核');$('#caseDetail').innerHTML=`<div class="eyebrow">CASE REVIEW / 人工審認</div><h2 style="margin-top:9px">${esc(c.id)} ${badge(c.tax)}</h2><p>${esc(c.scenario)}</p><div class="detailgrid"><div><small>行政區 / 標的</small>${esc(c.district)} / ${esc(c.target)}</div><div><small>承辦人</small>${esc(c.owner)}</div><div><small>模擬面積</small>${c.area===null?'未提供':fmt(c.area)+' m²'}</div><div><small>資料品質</small>${esc(c.dataQuality)}</div></div><h3>分類提示：${esc(c.category)}</h3>${c.reasons.map(r=>`<div class="reason">${esc(r.text)}<small>${esc(r.code)} · ${esc(r.source)}</small></div>`).join('')}<div class="notice warning">理由為規則示意，並非SHAP或實際AI輸出。請核對佐證資料後再回填稅務審認結果。</div><form id="feedbackForm"><label>審認結果<select id="reviewResult">${selectOptions(['請選擇','確認稅務異常','確認無稅務異常','待現勘','資料待補'],c.feedback?.result||'請選擇')}</select></label><label style="margin-top:13px">佐證與處理摘要<textarea id="reviewNote" required maxlength="500" placeholder="請填寫示範查核依據；勿輸入真實個資">${esc(c.feedback?.note||'')}</textarea></label><p class="help">待現勘／資料待補屬未定標籤，不會被當成正常樣本。覆核不觸發自動改課或自動重訓。</p><button class="primary">儲存覆核回饋</button></form>${c.feedback?`<div class="timeline"><p>上次覆核：${esc(c.feedback.at)}<br>${esc(c.feedback.result)} · ${esc(c.feedback.note)}</p></div>`:''}`;$('#caseDialog').showModal();$('#feedbackForm').onsubmit=e=>{e.preventDefault();if(!ATGAuth.requireLogin())return;const result=$('#reviewResult').value,note=$('#reviewNote').value.trim();if(result==='請選擇'||!note){toast('請選擇審認結果並填寫佐證摘要。');return;}c.feedback={result,note,at:stamp(),reviewer:'geoinfor',label_version:'LABEL-DEMO-0.1',prediction_version:'DEMO-CLASSIFIER-0.1'};c.status=result.startsWith('確認')?'已覆核':result;audit('覆核回饋',id,result);$('#caseDialog').close();render();toast('覆核結果已儲存在本機示範資料。');};}
function exportFile(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csvCell(v){let s=String(v??'');if(/^[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
function exportCases(){const list=filtered(),head=['案件編號','稅種','行政區','態樣','分類提示','資料品質','承辦人','狀態',...(filters.risk?['117模擬分數']:[])];const rows=list.map(c=>[c.id,c.tax,c.district,c.scenario,c.category,c.dataQuality,c.owner,c.status,...(filters.risk?[c.score??'不評分']:[])]);exportFile('ATG116_示範查詢清冊_V1.0.1.csv','\ufeff'+[head,...rows].map(r=>r.map(csvCell).join(',')).join('\r\n'),'text/csv;charset=utf-8');audit('匯出清冊','',`${list.length}件模擬案件`);toast(`已匯出 ${list.length} 件查詢結果。`);}
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else if(!quoted&&cell!==''){throw Error('CSV引號位置錯誤');}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('CSV引號未關閉');row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows;}
async function importCSV(file){if(!file)return;if(file.size>150000){toast('示範檔上限150KB。');return;}try{const rows=parseCSV((await file.text()).replace(/^\uFEFF/,''));if(rows[0]?.join(',')!=='case_id,tax_type,district,scenario')throw Error('欄位格式錯誤，僅接受四個示範欄位。');if(rows.length<2||rows.length>101)throw Error('示範匯入須為1至100筆案件。');const ids=new Set(cases.map(c=>c.id));const items=rows.slice(1).map((r,i)=>{if(r.length!==4)throw Error(`第${i+2}列欄位數錯誤`);const [id,tax,district,scenario]=r.map(v=>v.trim());if(!/^DEMO-\d{3,6}$/.test(id)||ids.has(id))throw Error(`第${i+2}列編號不符或重複`);if(!['房屋稅','地價稅'].includes(tax)||!district||district.length>8||!scenario||scenario.length>60)throw Error(`第${i+2}列內容格式錯誤`);ids.add(id);return {...structuredClone(ATG_SEED[0]),id,tax,district,scenario,target:'新匯入模擬標的',category:'需人工判斷',dataQuality:'待核對來源',status:'資料待補',owner:'未分派',score:null,area:null,reasons:[{code:'DQ-IMPORT-01',text:'新匯入示範案件尚未核對來源與標的，請先補正。',source:'本次示範CSV匯入'}],feedback:null,project:`116${tax}疑義清查`,x:90+(i*87)%570,y:95+(i*61)%400};});if(!ATGAuth.requireLogin())return;cases.push(...items);audit('批次匯入','',`${items.length}件模擬案件`);render();$('#importResult').textContent=`已匯入 ${items.length} 件，分類與來源待人工核對。`;}catch(e){$('#importResult').textContent='整批拒收：'+e.message;toast('匯入未完成，請檢查檔案。');}}
function bindMapPoints(){$$('.mapcase').forEach(g=>{const fn=()=>{selected=g.dataset.id;render();};g.onclick=fn;g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fn();}};});}
function redrawMap(){const opacity=$('#taxOpacity')?.value;$('#mapSvgHost').innerHTML=mapSVG();if(opacity!==undefined)$$('#demoMap g rect[opacity]').forEach(r=>r.setAttribute('opacity',opacity/100));bindMapPoints();}
function bind(){
$$('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go));$$('.openCase').forEach(b=>b.onclick=()=>openCase(b.dataset.id));$$('.locateCase').forEach(b=>b.onclick=()=>{selected=b.dataset.id;filters={tax:'全部',district:'全部',status:'全部',query:'',risk:false,min:70};audit('定位案件',selected,'模擬圖台');navigate('map');});
if($('#applyFilter')){$('#applyFilter').onclick=()=>{filters.tax=$('#taxFilter').value;filters.district=$('#districtFilter').value;filters.status=$('#statusFilter').value;filters.query=$('#caseSearch').value.trim();checked.clear();render();};$('#caseSearch').onkeydown=e=>{if(e.key==='Enter')$('#applyFilter').click();};$('#clearFilter').onclick=()=>{filters={tax:'全部',district:'全部',status:'全部',query:'',risk:false,min:70};checked.clear();render();};$('#riskToggle').onchange=e=>{filters.risk=e.target.checked;checked.clear();render();};if($('#scoreMin'))$('#scoreMin').onchange=e=>{filters.min=Number(e.target.value);checked.clear();render();};}
$$('.caseCheck').forEach(b=>b.onchange=()=>{b.checked?checked.add(b.dataset.id):checked.delete(b.dataset.id);if($('#selectedCount'))$('#selectedCount').textContent=`已選 ${checked.size} 件`;});if($('#selectAll'))$('#selectAll').onchange=e=>{$$('.caseCheck').forEach(c=>{c.checked=e.target.checked;c.dispatchEvent(new Event('change'));});};
if($('#exportCases'))$('#exportCases').onclick=exportCases;
if($('#assignCases'))$('#assignCases').onclick=()=>{if(!ATGAuth.requireLogin())return;const ids=filtered().filter(c=>checked.has(c.id));if(!ids.length){toast('請先選取要分派的案件。');return;}const owner=$('#assignOwner').value;ids.forEach(c=>{c.owner=owner;audit('案件派送',c.id,owner);});checked.clear();render();toast(`已將 ${ids.length} 件分派給 ${owner}。`);};
if($('#exportFeedback'))$('#exportFeedback').onclick=()=>{const payload={version:'1.0.1',synthetic:true,exported_at:stamp(),records:cases.filter(c=>c.feedback).map(c=>({case_id:c.id,tax_type:c.tax,...c.feedback,eligible_label:c.feedback.result.startsWith('確認')}))};exportFile('ATG116_示範覆核回饋_V1.0.1.json',JSON.stringify(payload,null,2),'application/json');audit('匯出回饋','',`${payload.records.length}筆示範回饋`);toast('已匯出回饋及標籤資格。');};
if($('#mapTax')){$('#mapTax').onchange=e=>{filters.tax=e.target.value;render();};$$('[data-layer]').forEach(b=>b.onchange=()=>{layers[b.dataset.layer]=b.checked;redrawMap();});$('#taxOpacity').oninput=redrawMap;$('#compareSlider').oninput=e=>{comparison=Number(e.target.value);redrawMap();};['yearFrom','yearTo'].forEach((id,i)=>$('#'+id).onchange=e=>{years[i]=e.target.value;$('#mapYears').textContent=`${years[0]} → ${years[1]} 年度 · 模擬比對`;});$('#zoomIn').onclick=()=>{zoom=Math.min(1.8,zoom+.2);redrawMap();};$('#zoomOut').onclick=()=>{zoom=Math.max(.7,zoom-.2);redrawMap();};$('#mapReset').onclick=()=>{zoom=1;redrawMap();};$('#parcelHistory').onclick=()=>{$('#caseDetail').innerHTML='<h2>地籍異動沿革（模擬）</h2><div class="timeline"><p>114：DEMO宗地-A</p><p>115：分割為 DEMO宗地-A1、A2</p><p>116：稅籍標的仍需對應新地號</p></div><p>正式版需保存異動原因、有效日期、面積權重及多對多地號關係；無對應則轉人工補正。</p>';$('#caseDialog').showModal();};bindMapPoints();}
$$('.propertyDetail').forEach(b=>b.onclick=()=>{$('#caseDetail').innerHTML=`<h2>公產 ${esc(b.dataset.type)}（模擬）</h2><p>比對來源：模擬產籍、地籍與年度使用分區快照。</p><div class="notice warning">請確認資料時點、合法使用依據與管理機關回覆。</div><label>管理機關釐正摘要<textarea id="propertyNote" placeholder="填寫示範釐正內容"></textarea></label><button id="saveProperty" class="primary" style="margin-top:15px">儲存釐正摘要</button>`;$('#caseDialog').showModal();$('#saveProperty').onclick=()=>{if(!ATGAuth.requireLogin())return;const note=$('#propertyNote').value.trim();if(!note){toast('請填寫釐正摘要。');return;}audit('公產釐正',b.dataset.type,note);$('#caseDialog').close();toast('釐正摘要已記錄至本機稽核。');};});
if($('#csvImport'))$('#csvImport').onchange=e=>importCSV(e.target.files[0]);
if($('#assistantForm')){const query=()=>{const q=$('#assistantQuery').value.trim();let items=cases;const known=['房屋稅','地價稅','待覆核','資料待補','已覆核'];if(!known.some(t=>q.includes(t))){$('#assistantAnswer').innerHTML='<div class="chat">目前僅支援房屋稅、地價稅、待覆核、資料待補、已覆核條件。此展示助手未串接LLM。</div>';return;}if(q.includes('房屋稅'))items=items.filter(c=>c.tax==='房屋稅');if(q.includes('地價稅'))items=items.filter(c=>c.tax==='地價稅');for(const st of ['待覆核','資料待補','已覆核'])if(q.includes(st))items=items.filter(c=>st==='資料待補'?c.dataQuality!=='完整'||c.status===st:c.status===st);$('#assistantAnswer').innerHTML=`<div class="chat">找到 ${items.length} 件。資料依據：本機模擬案件，查詢時間 ${esc(stamp())}。</div>${caseTable(items,false)}`;audit('智慧查詢','',q);$$('#assistantAnswer .openCase').forEach(b=>b.onclick=()=>openCase(b.dataset.id));$$('#assistantAnswer .locateCase').forEach(b=>b.onclick=()=>{selected=b.dataset.id;filters={tax:'全部',district:'全部',status:'全部',query:'',risk:false,min:70};navigate('map');});};$('#assistantForm').onsubmit=e=>{e.preventDefault();query();};$$('.promptBtn').forEach(b=>b.onclick=()=>{$('#assistantQuery').value=b.textContent;query();});}
if($('#exportLogs'))$('#exportLogs').onclick=()=>{exportFile('ATG116_示範稽核_V1.0.1.json',JSON.stringify({version:'1.0.1',synthetic:true,logs},null,2),'application/json');toast('已匯出本機稽核紀錄。');};
if($('#resetDemo'))$('#resetDemo').onclick=()=>{if(!confirm('重置本機模擬案件與回饋？既有來源檔不受影響。'))return;cases=structuredClone(ATG_SEED);logs=[];selected=cases[0].id;checked.clear();audit('重置展示','','恢復24件初始案件');render();toast('已重置展示。');};
}
$('#logout').onclick=()=>{audit('登出','','結束展示登入');ATGAuth.logout();};$('#closeDialog').onclick=()=>$('#caseDialog').close();
$$('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));
window.addEventListener('pageshow',()=>{if(ATGAuth.requireLogin())document.documentElement.hidden=false;});window.addEventListener('hashchange',()=>{page=location.hash.slice(1)||'dashboard';if(!titles[page])page='dashboard';render();});
setInterval(()=>{if(document.visibilityState==='visible')ATGAuth.requireLogin();},30000);
audit('登入','','本機POC工作台載入');page=location.hash.slice(1)||'dashboard';if(!titles[page])page='dashboard';render();
})();
