/* ATG POC V1.1.0 · 2026-10-04 · Synthetic workflow simulator. No network/model. */
'use strict';
window.ATGFlow = (() => {
  const KEY='atg116.flow.v1.1';
  const dictionary={H01:'商業設施疑未設籍或用途不符',H02:'租賃用途疑不一致',H03:'新增建物疑未完成設籍',L01:'田賦土地疑有非農用建物',L02:'田賦土地疑有太陽能設施',L03:'開工或利用變更疑未反映',L04:'減免土地使用疑不符'};
  const labelNames={CONFIRMED_ANOMALY:'確認稅務異常',CONFIRMED_NORMAL:'確認無稅務異常',PENDING:'待現勘／未完成',INSUFFICIENT:'資料不足',NOT_APPLICABLE:'不適用',DISPUTED:'爭議待裁決'};
  const terminal=['SUCCEEDED','INSUFFICIENT','NOT_APPLICABLE','FAILED','SKIPPED','CANCELLED'];
  const gates=['真值與範圍核定','獨立凍結測試','校準與覆核容量','影子比較','API與故障續作','回復與還原','風險及能力檢核'];
  const initial=()=>({version:'1.1.0',jobs:[],predictions:[],reviews:[],snapshots:[],sources:{},outbox:[],seq:0,online:true,role:'B1',champion:{房屋稅:'DEMO-H-R1',地價稅:'DEMO-L-R1'},releases:[],events:[],checks:{},risks:[],staff:[]});
  function create(ctx){
    const {$,$$}={ $:s=>document.querySelector(s), $$:s=>[...document.querySelectorAll(s)] };
    const {esc,audit,toast,render,navigate,exportFile}=ctx;
    let state;
    try{state=JSON.parse(localStorage.getItem(KEY));if(state?.version!=='1.1.0')state=initial();}catch{state=initial();}
    const now=()=>new Date().toISOString();
    const uid=prefix=>prefix+'-'+String(++state.seq).padStart(4,'0');
    const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state));}catch{toast('流程紀錄僅留於記憶體；瀏覽器儲存失敗。');}};
    const record=(action,id,detail)=>{state.events.unshift({at:now(),action,id,detail,role:state.role});save();audit(action,id,detail);};
    const chip=s=>`<span class="badge ${['FAILED','INSUFFICIENT','DISPUTED','COMPLETED_WITH_ERRORS'].includes(s)?'red':s.includes('PENDING')||s==='RETRY_WAIT'?'amber':''}">${esc(s)}</span>`;
    const patterns=c=>c.tax==='房屋稅'?(c.scenario.includes('租')?['H02']:c.scenario.includes('新增')||c.scenario.includes('新建')?['H03']:['H01','H03']):c.scenario.includes('太陽')?['L02']:c.scenario.includes('開工')||c.scenario.includes('變更')?['L03']:c.scenario.includes('減免')||c.scenario.includes('保留')?['L04']:['L01'];
    const schema=tax=>tax==='房屋稅'?'demo-house-v1':'demo-land-v1';
    const revision=id=>state.sources[id]||1;
    const latestReview=(id,pattern)=>state.reviews.filter(r=>r.case_id===id&&r.pattern===pattern).at(-1);
    const currentReviews=()=>state.reviews.filter(r=>latestReview(r.case_id,r.pattern)?.id===r.id);
    const approved=()=>currentReviews().filter(r=>r.approved_at&&['CONFIRMED_ANOMALY','CONFIRMED_NORMAL'].includes(r.label)&&r.revision===revision(r.case_id));
    const frame=()=>`<div class="flow-banner"><div><b>規格對照 V1.3 · 合成流程實驗室</b><small>操作保存在此瀏覽器；模型、API、worker與角色權限皆為示範。</small></div><label>模擬角色<select id="flowRole"><option value="B1" ${state.role==='B1'?'selected':''}>B1 承辦提報</option><option value="B" ${state.role==='B'?'selected':''}>B 業務核定</option><option value="Q" ${state.role==='Q'?'selected':''}>Q 獨立驗證</option><option value="O" ${state.role==='O'?'selected':''}>O 發布操作</option></select></label></div>`;
    const table=(heads,rows)=>`<div class="tablewrap"><table><thead><tr>${heads.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${heads.length}">尚無紀錄。</td></tr>`}</tbody></table></div>`;
    const numberCards=rows=>`<div class="cards">${rows.map(([label,val,detail])=>`<div class="card"><small>${esc(label)}</small><strong>${val}</strong><small>${esc(detail)}</small></div>`).join('')}</div>`;

    // A controlled fixture represents a validated snapshot. Browser fields never assert ownership.
    function makeJob(tax,fixture,sourceItems){
      const release=state.champion[tax], ids=ctx.getCases().filter(c=>c.tax===tax).slice(0,6);
      const items=sourceItems||ids.map((c,i)=>({case_id:c.id,revision:revision(c.id),pattern:patterns(c)[0],kind:['rule','rule','missing','notapp','skip','transient'][i],state:'PENDING',attempt:0}));
      const key=JSON.stringify([tax,fixture,release,schema(tax),'demo-threshold-v1','demo-rule-v1',items.map(i=>[i.case_id,i.revision,i.pattern])]);
      const old=state.jobs.find(j=>j.key===key);
      if(old){record('冪等重送',old.id,'回既有 job_id；不重建任務或候選');toast('202 DEMO：相同冪等鍵，回既有 '+old.id);return old;}
      const id=uid('DEMO-JOB');
      const job={id,tax,fixture,key,release,schema:schema(tax),snapshot:uid('DEMO-SNAPSHOT'),created_at:now(),items,checkpoint:0,state:'PENDING',raw:sourceItems?items.length:10,quarantine:sourceItems?0:1,scopePending:sourceItems?0:1,excludedPublic:sourceItems?0:1,excludedOther:sourceItems?0:1};
      state.jobs.push(job);state.outbox.push({id:uid('DEMO-EVENT'),job_id:id,state:'PENDING',snapshot:job.snapshot});
      record('受理分類任務',id,'202 DEMO；固定 '+release+'；快照及outbox同次保存');toast('202 DEMO：已受理 '+id);return job;
    }
    const counts=j=>Object.fromEntries([...terminal,'PENDING','RUNNING','RETRY_WAIT'].map(s=>[s,j.items.filter(i=>i.state===s).length]));
    function reconcile(j){const c=counts(j),done=terminal.reduce((n,k)=>n+c[k],0);j.checkpoint=done;j.state=done===j.items.length?(c.FAILED||c.CANCELLED||j.quarantine||j.scopePending?'COMPLETED_WITH_ERRORS':'COMPLETED'):(c.RUNNING?'RUNNING':c.RETRY_WAIT?'WAITING_RETRY':'PENDING');return {c,done};}
    function complete(j,item){
      const c=ctx.getCases().find(c=>c.id===item.case_id),current=revision(item.case_id);
      if(item.revision!==current||j.release!==state.champion[j.tax]){
        item.state='SKIPPED';item.reason=item.revision!==current?'STALE_REVISION':'STALE_RELEASE';
        state.predictions.push({id:uid('DEMO-PRED'),case_id:item.case_id,source_revision:item.revision,release_id:j.release,snapshot_id:j.snapshot,feature_schema_version:j.schema,current:false,decision:'STALE',probability:null,synthetic:true});
        makeJob(j.tax,'revision-'+current,[{...item,revision:current,state:'PENDING',attempt:0,kind:'rule',reason:null}]);
        record('舊版本隔離',j.id,'歷史保留；現行結果不覆寫，建立新版補跑');return;
      }
      if(!state.online){item.state='RETRY_WAIT';item.reason='503 MODEL_NOT_READY';item.retry_after='1、5、15分鐘（正式起始政策；POC手動推進）';return;}
      if(item.kind==='transient'&&item.attempt===1){item.state='RETRY_WAIT';item.reason='TIMEOUT';return;}
      item.state=item.kind==='missing'?'INSUFFICIENT':item.kind==='notapp'?'NOT_APPLICABLE':item.kind==='skip'?'SKIPPED':'SUCCEEDED';
      item.reason={missing:'REQUIRED_EVIDENCE_MISSING',notapp:'PATTERN_NOT_APPLICABLE',skip:'UNCHANGED_SNAPSHOT'}[item.kind]||'DEMO_RULE_MATCH';
      if(item.state!=='SKIPPED'){
        const pred={id:uid('DEMO-PRED'),case_id:item.case_id,tax_type:j.tax==='房屋稅'?'HOUSE_TAX':'LAND_VALUE_TAX',snapshot_id:j.snapshot,source_revision:item.revision,release_id:j.release,feature_schema_version:j.schema,threshold_version:'demo-threshold-v1',rule_version:'demo-rule-v1',decision:item.state==='SUCCEEDED'?'RULE_ONLY':item.state,patterns:[{code:item.pattern,probability:null,threshold:null}],rule_reasons:[item.reason],data_quality:{status:item.kind==='missing'?'insufficient':'valid',missing:item.kind==='missing'?['demo_required_evidence']:[]},current:true,synthetic:true};
        state.predictions.filter(p=>p.case_id===item.case_id&&p.patterns?.some(p=>p.code===item.pattern)).forEach(p=>p.current=false);
        state.predictions.push(pred);item.prediction_id=pred.id;
        if(c){c.category=item.state==='INSUFFICIENT'?'需補證據':item.state==='NOT_APPLICABLE'?'本態樣不適用':'規則候選提示';c.dataQuality=item.state==='INSUFFICIENT'?'資料待補':c.dataQuality;c.status=item.state==='INSUFFICIENT'?'資料待補':'待覆核';}
      }
    }
    function step(j){
      if(!ATGAuth.requireLogin())return;
      const active=j.items.find(i=>i.state==='RUNNING');
      if(active){complete(j,active);record('保存任務結果',j.id,active.case_id+' '+active.state);}
      else{const item=j.items.find(i=>i.state==='PENDING');if(!item){toast('沒有可領取項；待重試項需先手動重派。');return;}item.state='RUNNING';item.attempt++;item.lease_until='DEMO：下一次推進或重啟釋放';state.outbox.filter(e=>e.job_id===j.id).forEach(e=>e.state='DISPATCHED');record('worker領取',j.id,item.case_id+'；短交易租約示意');}
      reconcile(j);save();render();
    }
    function jobsView(){
      state.jobs.forEach(reconcile);
      return frame()+`<section class="panel"><div class="panelhead"><h2>匯入後分類任務</h2>${chip(state.online?'DEMO READY':'DEMO 503')}</div><p>受控合成快照每稅別10列：6列可建立任務，格式隔離、權屬待確認、公有排除、其他稅別排除各1列。僅示範流程；沒有上傳正式稅檔。</p><div class="filters"><label>稅別<select id="jobTax"><option>房屋稅</option><option>地價稅</option></select></label><label>合成快照<select id="jobFixture"><option value="DEMO-116-A">DEMO-116-A</option><option value="DEMO-116-B">DEMO-116-B</option></select></label><button id="createJob" class="primary">受理批次（202示意）</button><button id="toggleService">${state.online?'模擬API 503':'恢復示範服務'}</button></div><div class="flow"><span>1 範圍／格式校驗</span><span>2 快照＋outbox</span><span>3 dispatcher／租約</span><span>4 規則／品質判斷</span><span>5 結果／覆核候選</span></div></section>`+state.jobs.slice().reverse().map(j=>{
        const {c,done}=reconcile(j),rawSum=j.quarantine+j.scopePending+j.excludedPublic+j.excludedOther+j.items.length;
        return `<section class="panel job-panel" data-job-panel="${j.id}"><div class="panelhead"><h2>${esc(j.id)} · ${esc(j.tax)}</h2>${chip(j.state)}</div><p class="help">快照 ${esc(j.snapshot)} · 固定 release ${esc(j.release)} · ${esc(j.schema)}</p><div class="progress" aria-label="任務完成率"><span style="width:${done/j.items.length*100}%"></span></div><p>${done}/${j.items.length} 已達終態；checkpoint=${j.checkpoint}。${c.RETRY_WAIT?'待重試 '+c.RETRY_WAIT+' 件；未視為正常或完成。':''}</p>${numberCards([['有效來源列',j.raw,'原始列與任務分開對帳'],['隔離／範圍待確認',j.quarantine+j.scopePending,'尚有待處理列'],['排除公有／其他稅別',j.excludedPublic+j.excludedOther,'不進分類、覆核或訓練'],['合格任務',j.items.length,'本fixture每列一個任務']])}<p class="reconciliation">raw ${j.raw} = 隔離 ${j.quarantine} + 範圍待查 ${j.scopePending} + 公有排除 ${j.excludedPublic} + 其他稅別排除 ${j.excludedOther} + eligible ${j.items.length}　${j.raw===rawSum?'✓':'✕'}</p><p class="reconciliation">eligible ${j.items.length} = 成功 ${c.SUCCEEDED} + 資料不足 ${c.INSUFFICIENT} + 不適用 ${c.NOT_APPLICABLE} + 失敗 ${c.FAILED} + 略過 ${c.SKIPPED} + 取消 ${c.CANCELLED} + 尚未完成 ${c.PENDING+c.RUNNING+c.RETRY_WAIT}</p><div class="actions"><button data-step="${j.id}" ${done===j.items.length?'disabled':''}>推進一個步驟</button><button data-retry="${j.id}" ${!c.RETRY_WAIT&&!c.FAILED?'disabled':''}>重派待重試／失敗</button><button data-restart="${j.id}" ${!c.RUNNING?'disabled':''}>模擬worker重啟</button><button data-revise="${j.id}" ${!c.RUNNING?'disabled':''}>模擬來源revision更新</button><button data-cancel="${j.id}" ${done===j.items.length?'disabled':''}>取消未完成項</button><button data-job-export="${j.id}">匯出任務JSON</button></div>${table(['案件／態樣','revision','狀態','attempt','原因／結果'],j.items.map(i=>[esc(i.case_id)+'<br>'+esc(i.pattern),esc(i.revision),chip(i.state),i.attempt,esc(i.reason||'—')+'<br><small>'+esc(i.prediction_id||'')+'</small>']))}</section>`;
      }).join('')+(!state.jobs.length?'<section class="panel empty">先受理一批合成快照，即可體驗503重試、重啟續作及revision競態。</section>':'');
    }

    function openCase(id){
      const c=ctx.getCases().find(c=>c.id===id);if(!c)return;
      const codes=patterns(c),pred=state.predictions.filter(p=>p.case_id===id&&p.current).at(-1);
      audit('查看案件',id,'態樣覆核與版本追溯');
      $('#caseDetail').innerHTML=`<div class="eyebrow">PATTERN REVIEW / 合成案件</div><h2>${esc(c.id)} · ${esc(c.tax)}</h2><p>${esc(c.scenario)}</p><div class="detailgrid"><div><small>業務標的</small>${esc(c.target)}</div><div><small>來源revision／資料基準日</small>${revision(id)} ／ 2027-01-15（合成）</div><div><small>預測版本／資料品質</small>${esc(pred?.release_id||state.champion[c.tax])} ／ ${esc(c.dataQuality)}</div><div><small>匹配／權屬範圍</small>示範關聯 ／ IN_SCOPE（受控fixture）</div></div><label class="layercheck"><input type="checkbox" id="blindReview">盲核模式：隱藏規則提示與建議</label><div id="reviewHints">${table(['態樣','示範輸出','機率／門檻'],codes.map(code=>[esc(code)+' '+esc(dictionary[code]),chip(c.dataQuality==='完整'?'RULE_ONLY':'INSUFFICIENT'),'null ／ null']))}<p class="help">尚未訓練模型；規則提示不形成正常或異常真值。各態樣獨立判斷。</p>${c.reasons.map(r=>`<div class="reason">${esc(r.text)}<small>${esc(r.code)} · 合成規則原因</small></div>`).join('')}</div><form id="feedbackForm"><div class="filters"><label>本次覆核態樣<select id="reviewPattern">${codes.map(code=>`<option value="${code}">${code} ${esc(dictionary[code])}</option>`).join('')}</select></label><label>審認結果<select id="reviewResult"><option value="">請選擇</option>${Object.entries(labelNames).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label></div><div class="filters"><label>業務有效日期<input id="reviewEffective" type="date" value="2027-01-15" required></label><label>理由代碼<select id="reviewReason"><option value="">請選擇</option><option value="EVIDENCE_CONFIRMED">已核對同時點證據</option><option value="LEGAL_EXCEPTION">合法適用例外</option><option value="MISSING_EVIDENCE">必要證據待補</option><option value="OUTSIDE_PATTERN">本態樣不適用</option><option value="REVIEW_DISAGREEMENT">覆核意見分歧</option></select></label></div><label>證據參照（僅DEMO-代碼）<input id="reviewEvidence" placeholder="DEMO-EVIDENCE-001" pattern="DEMO-[A-Za-z0-9-]+" required maxlength="80"></label><label>佐證與處理摘要<textarea id="reviewNote" required maxlength="500" placeholder="僅填合成查核摘要，勿輸入真實個資"></textarea></label><p class="help">提報角色B1先留版本，再由角色B核定。正常結論同樣需要證據；未核定、待查、爭議及不適用均不進訓練。</p><button class="primary">提報覆核回饋</button><div id="reviewMessage" role="status"></div></form><h3 style="margin-top:20px">本案態樣歷程</h3>${reviewTable(state.reviews.filter(r=>r.case_id===id),false)}`;
      $('#caseDialog').showModal();$('#blindReview').onchange=e=>$('#reviewHints').hidden=e.target.checked;
      $('#feedbackForm').onsubmit=e=>{
        e.preventDefault();if(!ATGAuth.requireLogin())return;
        const msg=$('#reviewMessage');if(state.role!=='B1'){msg.textContent='此操作需模擬角色B1；請於標籤頁切換。';return;}
        const pattern=$('#reviewPattern').value,label=$('#reviewResult').value,evidence=$('#reviewEvidence').value.trim(),note=$('#reviewNote').value.trim(),reason=$('#reviewReason').value,effective=$('#reviewEffective').value;
        if(!label||!note||!reason||!effective||!/^DEMO-[A-Za-z0-9-]+$/.test(evidence)){msg.textContent='請補齊態樣、結果、日期、理由、DEMO證據與摘要。';return;}
        const patternPred=state.predictions.filter(p=>p.case_id===id&&p.current&&p.patterns?.some(p=>p.code===pattern)).at(-1);
        const prior=latestReview(id,pattern),r={id:uid('DEMO-LABEL'),case_id:id,tax:c.tax,pattern,label,evidence,note,reason,effective_at:effective,reviewed_at:now(),reviewer:'DEMO-B1',approver:null,approved_at:null,label_version:'demo-label-v1',supersedes:prior?.id||null,revision:revision(id),prediction_id:patternPred?.id||'DEMO-RULE-PREVIEW',sampling:'DEMO-STRATIFIED',snapshot_id:patternPred?.snapshot_id||'DEMO-CASE-SNAPSHOT'};
        state.reviews.push(r);c.feedback={result:labelNames[label],note,at:r.reviewed_at,label_version:r.label_version,prediction_version:r.prediction_id,approved:false};c.status=['INSUFFICIENT','PENDING'].includes(label)?'資料待補':label==='DISPUTED'?'爭議待裁決':'承辦已提報';
        record('承辦提報',id,pattern+' '+label+'；歷史版本新增');$('#caseDialog').close();render();toast('提報已保存；尚未形成核定真值。');
      };
    }
    function reviewTable(rows,actions=true){return table(['標籤版本／案件','稅別／態樣','結論／核定狀態','有效日期／證據','版本關聯','操作'],rows.slice().reverse().map(r=>[esc(r.id)+'<br>'+esc(r.case_id),esc(r.tax)+' / '+esc(r.pattern),esc(labelNames[r.label])+'<br>'+chip(latestReview(r.case_id,r.pattern)?.id!==r.id?'SUPERSEDED':r.revision!==revision(r.case_id)?'STALE_SOURCE':r.approved_at?'APPROVED':'SUBMITTED'),esc(r.effective_at)+'<br>'+esc(r.evidence),esc(r.supersedes||'首版')+'<br><small>'+esc(r.prediction_id)+'</small>',actions&&!r.approved_at&&latestReview(r.case_id,r.pattern)?.id===r.id&&r.revision===revision(r.case_id)?`<button data-approve="${r.id}">業務核定</button>`:'—']));}
    function labelingView(){return frame()+numberCards([['承辦已提報',currentReviews().filter(r=>!r.approved_at).length,'先提報，後核定'],['可供合成訓練快照',approved().length,'核定正負標籤且revision一致'],['待查／爭議等',currentReviews().filter(r=>!['CONFIRMED_ANOMALY','CONFIRMED_NORMAL'].includes(r.label)).length,'不當作正常樣本'],['已凍結快照',state.snapshots.length,'後續修正不改寫舊快照']])+`<section class="panel"><div class="panelhead"><h2>態樣標籤核定</h2><button data-go="cases">開啟案件提報</button></div><p>H01–H03與L01–L04分開審認。同一案件未覆核的其他態樣仍為未知；個別態樣正常不推定整案正常。</p>${reviewTable(state.reviews)}<div class="actions" style="margin-top:18px"><button id="freezeLabels" class="primary">凍結核定標籤快照</button><button id="exportLabels">匯出態樣回饋</button></div><div id="labelMessage" role="status"></div></section><section class="panel"><h2>不可回寫的合成標籤快照</h2>${table(['快照','建立時間','房屋稅／地價稅','狀態','下載'],state.snapshots.map(s=>[esc(s.id),esc(s.at),s.records.filter(r=>r.tax==='房屋稅').length+' / '+s.records.filter(r=>r.tax==='地價稅').length,chip('DEMO_FROZEN'),`<button data-snapshot="${s.id}">JSON</button>`]))}<p class="help">快照只展示納入條件；沒有執行模型訓練。正式標籤須經具名權限、雙人覆核與證據稽核。</p></section>`;}
    function exportLabels(){exportFile('ATG116_態樣回饋_V1.1.0.json',JSON.stringify({version:'1.1.0',synthetic:true,records:state.reviews.map(r=>({...r,eligible_label:approved().some(a=>a.id===r.id)}))},null,2),'application/json');}

    function releaseView(){return frame()+`<section class="panel"><div class="panelhead"><h2>兩稅別發布指標</h2>${chip('NO TRAINED MODEL')}</div><div class="gridEqual">${Object.entries(state.champion).map(([tax,id])=>`<div class="release-card"><small>${esc(tax)} champion（合成指標）</small><h2>${esc(id)}</h2><p>${esc(schema(tax))} · RULE_ONLY<br>機率 null · 無真實效能指標</p></div>`).join('')}</div><div class="filters"><label>候選稅別<select id="releaseTax"><option>房屋稅</option><option>地價稅</option></select></label><label>相容性fixture<select id="releaseSchema"><option value="compatible">現行schema相容</option><option value="incompatible">不同schema（測試阻擋）</option></select></label><button id="createCandidate" class="primary">建立合成candidate</button></div><p class="help">候選按「檢核→影子→核准→切換」推進。舊任務固定原release；版本回復也必須通過相容性檢核。</p></section>`+state.releases.slice().reverse().map(r=>`<section class="panel"><div class="panelhead"><h2>${esc(r.id)} · ${esc(r.tax)}</h2>${chip(r.stage)}</div><p>特徵 ${esc(r.schema)} · 規則 demo-rule-v1 · 門檻 demo-threshold-v1 · 模型、校準器及評估：未建置。</p><div class="gate-grid">${gates.map((g,i)=>`<label class="layercheck"><input type="checkbox" data-gate="${r.id}" data-index="${i}" ${r.gates[i]?'checked':''} ${r.stage!=='CANDIDATE'?'disabled':''}>${esc(g)}（合成fixture）</label>`).join('')}</div><div class="actions"><button data-shadow="${r.id}">檢核並進入影子比較</button><button data-shadow-done="${r.id}">完成合成影子回放</button><button data-release-approve="${r.id}">核准候選</button><button data-publish="${r.id}">切換champion</button><button data-rollback="${r.id}">回復前版</button></div><p class="help">影子只保存合成差異紀錄；不改案件、不影響champion。正式影子期、量化門檻及容量由機關核定。</p>${r.shadow?table(['比較快照','規則一致／差異','是否改寫現行','效能結論'],[['DEMO-SHADOW-01','5 ／ 1（合成）','否','未量測真實Precision／Recall']]):''}</section>`).join('')+`<section class="panel"><h2>發布及回復歷程</h2>${table(['時間','操作角色','動作','版本','摘要'],state.events.filter(e=>/候選|影子|發布|回復/.test(e.action)).map(e=>[esc(e.at),esc(e.role),esc(e.action),esc(e.id),esc(e.detail)]))}</section>`;}
    const riskSeed=[
      ['R05','C 標註','真值不足或取樣偏差','B / M',5,4,'雙核、正常對照與未命中抽查'],
      ['R14','E 整合','事件遺失或版本競態','A / D',4,4,'outbox、冪等與舊revision故障fixture'],
      ['R16','E Windows','AP競用資源','O',4,4,'雙負載量測與worker併發限制'],
      ['R17','E Linux','跨機連線中斷','O / A',3,4,'503重試、憑證與隔網復原'],
      ['R20','F 上線','將規則提示誤作正式結論','B',3,5,'疑似／待查／核定狀態操作演練'],
      ['R22','G 回饋','錯誤自動學習或回饋污染','B / S',3,5,'核定快照、版本稽核及裁決'],
      ['R23','全程','能力或代理人未到位','P',4,4,'實作檢核、工時及交接重建']
    ];
    const staffSeed=[['B','業務主管／裁決','合法例外、有效日期與兩稅別核定'],['B1','承辦／標註','匿名案件判讀、理由與證據'],['P','專案／需求','相依排程、追溯與風險'],['D','資料工程','鍵值、快照、scope與對帳'],['G','GIS','CRS、面積、歧義與圖層時點'],['M','模型工程','分組時間切分、校準與獨立測試'],['A','後端介接','冪等、revision競態與503'],['O','維運／MLOps','選定OS啟停、還原與雙負載'],['S','資安／保管','授權、secret、拒絕測試與供應鏈'],['Q','獨立驗證','找出洩漏、自我驗收與證據缺口']];
    function risksView(){
      if(!state.risks.length)state.risks=riskSeed.map(r=>({id:r[0],phase:r[1],name:r[2],owner:r[3],l:r[4],i:r[5],control:r[6],evidence:'',status:'待驗證'}));
      if(!state.staff.length)state.staff=staffSeed.map(s=>({id:s[0],role:s[1],skill:s[2],status:'待檢核',evidence:'',backup:''}));save();
      const blockers=state.risks.filter(r=>r.status!=='受控監測').length,missing=state.staff.filter(s=>s.status!=='通過'||!s.backup).length;
      return frame()+numberCards([['風險控制待驗證',blockers,'規劃初評，不是實測發生率'],['能力／代理待補',missing,'角色具名與實作另行核定'],['發布阻擋',blockers+missing?'尚未排除':'合成條件通過','正式發布仍需後端權限與真實證據'],['V1.3對照', '16 / 17','風險章／人員能力章']])+`<section class="panel"><h2>階段風險與控制證據</h2><p>R=L×I供同專案排序。此處僅提供7筆合成風險範例；控制未驗證前不降低風險。資料外流、範圍污染、未知當正常、不可重建與越權正式處理列阻擋條件。</p>${table(['risk／階段','風險／主責','初評L×I','控制與證據','狀態','紀錄'],state.risks.map(r=>[esc(r.id)+'<br>'+esc(r.phase),esc(r.name)+'<br>'+esc(r.owner),r.l+'×'+r.i+' = '+r.l*r.i,esc(r.control)+`<input aria-label="${r.id}證據" data-risk-evidence="${r.id}" value="${esc(r.evidence)}" placeholder="DEMO-TEST-01">`,chip(r.status),`<button data-risk-verify="${r.id}">驗證控制</button>`]))}</section><section class="panel"><h2>能力、代理與職務分離</h2><p>角色B核定標籤、Q驗證、O發布；同一模型作者不單獨核定自身模型。此頁是規劃及合成證據填寫，不能視為人員已到位或採購資格。</p>${table(['角色','必備實作能力','代理／合成證據','檢核狀態','紀錄'],state.staff.map(s=>[esc(s.id)+' '+esc(s.role),esc(s.skill),`<input aria-label="${s.id}代理" data-backup="${s.id}" value="${esc(s.backup)}" placeholder="DEMO-BACKUP-${s.id}"><input aria-label="${s.id}能力證據" data-staff-evidence="${s.id}" value="${esc(s.evidence)}" placeholder="DEMO-TEST-${s.id}">`,chip(s.status),`<button data-staff-pass="${s.id}">記錄檢核通過</button>`]))}<button id="exportRisk" style="margin-top:18px">匯出風險與能力快照</button></section><section class="panel"><h2>A–G階段審查</h2><div class="flow">${['A 定義／授權','B 資料／規則','C 正負真值','D 訓練／量化','E API／故障','F 影子／核定','G 監測／重訓'].map(x=>`<span>${x}</span>`).join('')}</div><p class="help" style="margin-top:16px">每階段各自查核證據；前一階段通過不代表後續自動核准。POC目前只驗證合成操作行為。</p></section>`;
    }
    function scopeView(){return `<section class="panel"><h2>分類範圍已依 V1.3 調整</h2><div class="notice">AI分類、人工覆核、標籤與模型驗收限定房屋稅與地價稅。公有房地及其他稅別不納入；本版移除先前公產示範操作。</div>${table(['受控快照狀態','路由','模型機率','是否進覆核／訓練'],[['IN_SCOPE','H01–H03 ／ L01–L04','本POC皆為null','可進覆核；核定正負標籤才可進快照'],['EXCLUDED_PUBLIC_PROPERTY','公有房地排除','不執行模型','否'],['EXCLUDED_OTHER_DOMAIN','其他稅別排除','不執行模型','否'],['SCOPE_PENDING','權屬或範圍未知，先補證','不執行模型','否'],['QUARANTINED','格式隔離與修正','不執行模型','否']])}<p>權屬旗標須由後端受控資料產生；前端不提供任意勾選納入按鈕。排除與待確認列在批次作業另行對帳。</p><button data-go="jobs">開啟批次範圍對帳</button></section>`;}

    const byId=id=>state.jobs.find(j=>j.id===id);
    function bind(){
      if($('#flowRole'))$('#flowRole').onchange=e=>{state.role=e.target.value;save();toast('已切換模擬角色；此選單不代表正式授權。');};
      if($('#createJob'))$('#createJob').onclick=()=>{makeJob($('#jobTax').value,$('#jobFixture').value);render();};
      if($('#toggleService'))$('#toggleService').onclick=()=>{state.online=!state.online;record('服務狀態模擬','','DEMO '+(state.online?'READY':'503'));render();};
      $$('[data-step]').forEach(b=>b.onclick=()=>step(byId(b.dataset.step)));
      $$('[data-retry]').forEach(b=>b.onclick=()=>{const j=byId(b.dataset.retry);j.items.filter(i=>['RETRY_WAIT','FAILED'].includes(i.state)).forEach(i=>{i.state=i.attempt>=3?'FAILED':'PENDING';if(i.state==='FAILED')i.reason='DEAD_LETTER_MAX_ATTEMPTS';});record('任務重派',j.id,'重試上限3次；終態保留');reconcile(j);save();render();});
      $$('[data-restart]').forEach(b=>b.onclick=()=>{const j=byId(b.dataset.restart);j.items.filter(i=>i.state==='RUNNING').forEach(i=>{i.state='PENDING';i.reason='LEASE_RECOVERED';});record('worker重啟模擬',j.id,'釋放租約、保留已完成checkpoint');reconcile(j);save();render();});
      $$('[data-revise]').forEach(b=>b.onclick=()=>{const j=byId(b.dataset.revise),i=j.items.find(i=>i.state==='RUNNING');if(!i)return;state.sources[i.case_id]=revision(i.case_id)+1;state.predictions.filter(p=>p.case_id===i.case_id).forEach(p=>p.current=false);record('來源更新',i.case_id,'current_revision='+revision(i.case_id));render();});
      $$('[data-cancel]').forEach(b=>b.onclick=()=>{const j=byId(b.dataset.cancel);j.items.filter(i=>!terminal.includes(i.state)).forEach(i=>{i.state='CANCELLED';i.reason='USER_CANCELLED';});record('取消任務',j.id,'保留成功與取消計數');reconcile(j);save();render();});
      $$('[data-job-export]').forEach(b=>b.onclick=()=>{const j=byId(b.dataset.jobExport);exportFile(j.id+'.json',JSON.stringify({version:'1.1.0',synthetic:true,job:j,predictions:state.predictions.filter(p=>j.items.some(i=>i.prediction_id===p.id))},null,2),'application/json');});
      $$('[data-approve]').forEach(b=>b.onclick=()=>{if(state.role!=='B'){toast('核定需要模擬角色B；提報與核定分開。');return;}const r=state.reviews.find(r=>r.id===b.dataset.approve);if(!r||r.revision!==revision(r.case_id)||latestReview(r.case_id,r.pattern)?.id!==r.id)return;r.approved_at=now();r.approver='DEMO-B';const c=ctx.getCases().find(c=>c.id===r.case_id);if(c?.feedback)c.feedback.approved=true;if(c){const rs=patterns(c).map(code=>latestReview(c.id,code));c.status=rs.some(v=>v?.label==='DISPUTED')?'爭議待裁決':rs.every(v=>v?.approved_at&&['CONFIRMED_ANOMALY','CONFIRMED_NORMAL'].includes(v.label))?'已覆核':rs.some(v=>v?.approved_at&&['CONFIRMED_ANOMALY','CONFIRMED_NORMAL'].includes(v.label))?'部分態樣已覆核':'資料待補';}record('業務核定',r.id,r.pattern+' '+r.label);render();});
      if($('#freezeLabels'))$('#freezeLabels').onclick=()=>{if(state.role!=='B'){toast('凍結需要模擬角色B。');return;}const rows=approved();if(!rows.length){$('#labelMessage').textContent='尚無核定且revision有效的正負標籤，禁止建立空白訓練快照。';return;}state.snapshots.push({id:uid('DEMO-LABEL-SNAPSHOT'),at:now(),synthetic:true,records:structuredClone(rows)});record('凍結標籤快照','','僅納入 '+rows.length+' 筆已核定正負標籤');render();};
      if($('#exportLabels'))$('#exportLabels').onclick=exportLabels;
      $$('[data-snapshot]').forEach(b=>b.onclick=()=>exportFile(b.dataset.snapshot+'.json',JSON.stringify(state.snapshots.find(s=>s.id===b.dataset.snapshot),null,2),'application/json'));
      if($('#createCandidate'))$('#createCandidate').onclick=()=>{const tax=$('#releaseTax').value,r={id:uid(tax==='房屋稅'?'DEMO-H-CANDIDATE':'DEMO-L-CANDIDATE'),tax,schema:$('#releaseSchema').value==='compatible'?schema(tax):'demo-incompatible-v2',stage:'CANDIDATE',gates:gates.map(()=>false),shadow:false,previous:null};state.releases.push(r);record('建立候選',r.id,'純合成包，未訓練模型');render();};
      $$('[data-gate]').forEach(b=>b.onchange=()=>{const r=state.releases.find(r=>r.id===b.dataset.gate);if(state.role!=='Q'){b.checked=r.gates[+b.dataset.index];toast('檢核證據需要模擬角色Q。');return;}if(+b.dataset.index===6&&(!state.risks.length||state.risks.some(r=>r.status!=='受控監測')||state.staff.length!==10||state.staff.some(s=>s.status!=='通過'||!s.backup))){b.checked=false;toast('風險／能力阻擋：請先完成風險與人員檢核頁的合成證據。');return;}r.gates[+b.dataset.index]=b.checked;record('候選檢核',r.id,gates[+b.dataset.index]+'：'+b.checked);});
      const releaseAction=(selector,fn)=>$$(selector).forEach(b=>b.onclick=()=>{const id=Object.values(b.dataset)[0],r=state.releases.find(r=>r.id===id);if(r)fn(r);save();render();});
      releaseAction('[data-shadow]',r=>{if(state.role!=='Q'||r.stage!=='CANDIDATE'||!r.gates.every(Boolean)){toast('影子進入阻擋：需Q及7項檢核。');return;}if(r.schema!==schema(r.tax)){record('候選發布阻擋',r.id,'FEATURE_SCHEMA_MISMATCH');toast('特徵schema不相容，禁止進入影子或發布。');return;}r.stage='SHADOW';record('影子開始',r.id,'champion不變；案件結果不回寫');});
      releaseAction('[data-shadow-done]',r=>{if(state.role!=='Q'||r.stage!=='SHADOW'){toast('需Q完成影子中的候選。');return;}r.shadow=true;r.stage='VALIDATED';record('影子回放完成',r.id,'合成快照：5一致、1差異；不構成真實模型效能');});
      releaseAction('[data-release-approve]',r=>{if(state.role!=='B'||r.stage!=='VALIDATED'){toast('候選核准需B及已完成影子驗證。');return;}r.stage='APPROVED';record('候選核准',r.id,'DEMO-B合成核准');});
      releaseAction('[data-publish]',r=>{if(state.role!=='O'||r.stage!=='APPROVED'||r.schema!==schema(r.tax)){toast('發布阻擋：需O、核准候選及相容schema。');return;}r.previous=state.champion[r.tax];state.champion[r.tax]=r.id;r.stage='PUBLISHED';record('發布切換',r.id,'previous='+r.previous+'；既有任務release不變');});
      releaseAction('[data-rollback]',r=>{if(state.role!=='O'||r.stage!=='PUBLISHED'||state.champion[r.tax]!==r.id||!r.previous||r.schema!==schema(r.tax)){toast('回復阻擋：需O、現行版本與相容前版。');return;}state.champion[r.tax]=r.previous;r.stage='ROLLED_BACK';record('相容回復',r.id,'恢復 '+r.previous+'；歷史結果保留');});
      $$('[data-risk-verify]').forEach(b=>b.onclick=()=>{const r=state.risks.find(r=>r.id===b.dataset.riskVerify),e=$('[data-risk-evidence="'+r.id+'"]').value.trim();if(state.role!=='Q'||!/^DEMO-[A-Za-z0-9-]+$/.test(e)){toast('需Q角色與DEMO證據代碼；不能以口頭承諾結案。');return;}r.evidence=e;r.status='受控監測';record('風險控制驗證',r.id,'合成證據 '+e+'；初評分數保留');render();});
      $$('[data-staff-pass]').forEach(b=>b.onclick=()=>{const s=state.staff.find(s=>s.id===b.dataset.staffPass),e=$('[data-staff-evidence="'+s.id+'"]').value.trim(),backup=$('[data-backup="'+s.id+'"]').value.trim();if(state.role!=='Q'||![e,backup].every(v=>/^DEMO-[A-Za-z0-9-]+$/.test(v))){toast('需Q角色、DEMO實作證據及代理代碼。');return;}s.evidence=e;s.backup=backup;s.status='通過';record('能力檢核',s.id,'合成實作與代理 '+backup);render();});
      if($('#exportRisk'))$('#exportRisk').onclick=()=>exportFile('ATG116_風險與能力_V1.1.0.json',JSON.stringify({version:'1.1.0',synthetic:true,risks:state.risks,staff:state.staff},null,2),'application/json');
    }
    return {titles:{jobs:['批次分類作業','範圍對帳、固定版本、租約續作、重試與來源競態。'],labeling:['標籤核定與快照','各態樣提報、核定、歷史修正與受控訓練資料。'],release:['模型發布與回復','候選檢核、影子比較、業務核准及相容回復。'],risks:['風險及人員檢核','V1.3階段風險、控制證據、能力及代理管理。']},views:{jobs:jobsView,labeling:labelingView,release:releaseView,risks:risksView},bind,openCase,scopeView,exportLabels,patternSummary:c=>patterns(c).join(' / '),approvedCount:()=>approved().length,labelCounts:()=>({anomaly:approved().filter(r=>r.label==='CONFIRMED_ANOMALY').length,normal:approved().filter(r=>r.label==='CONFIRMED_NORMAL').length}),reset:()=>{state=initial();save();}};
  }
  return {create};
})();
